services:
  tinyproxy:
    image: travix/tinyproxy
    container_name: tinyproxy
    ports:
      - 8888:8888
    volumes:
      - ./tinyproxy.conf:/etc/tinyproxy.conf:ro
      - ./blocked-domains.txt:/etc/tinyproxy/blocked-domains.txt:ro
      - ./allowed-domains.txt:/etc/tinyproxy/allowed-domains.txt:ro
      - /data/tinyproxy-logs:/var/log/tinyproxy
      - /usr/share/zoneinfo:/usr/share/zoneinfo:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - TZ=Europe/Berlin
    restart: unless-stopped
    networks:
      - codersrv_default
  tinyproxy-gui:
    build: ./gui
    container_name: tinyproxy-gui
    ports:
      - 8080:80
    volumes:
      - ./blocked-domains.txt:/app/blocked-domains.txt
      - ./allowed-domains.txt:/app/allowed-domains.txt
      - ./traffic-history.json:/app/traffic-history.json
      - ./traffic-noise-filters.txt:/app/traffic-noise-filters.txt
      - ./tinyproxy.conf:/app/tinyproxy.conf
      - ./allowed-containers.txt:/app/allowed-containers.txt
      - ./blocked-containers.txt:/app/blocked-containers.txt
      - ./proxy-config.json:/app/proxy-config.json
      - /data/tinyproxy-logs:/var/log/tinyproxy:ro
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - TINYPROXY_CONTAINER=tinyproxy
      - TZ=Europe/Berlin
    restart: unless-stopped
    networks:
      - codersrv_default
volumes:
  tinyproxy-logs: null
networks:
  proxy-net:
    driver: bridge
  codersrv_default:
    external: true
