User tinyproxy
Group tinyproxy
Port 8888
Timeout 600
DefaultErrorFile "/usr/share/tinyproxy/default.html"
StatFile "/usr/share/tinyproxy/stats.html"
LogFile "/var/log/tinyproxy/tinyproxy.log"
LogLevel Info
PidFile "/var/run/tinyproxy/tinyproxy.pid"
MaxClients 100
MinSpareServers 5
MaxSpareServers 20
StartServers 10
MaxRequestsPerChild 0

# Allow access from specific containers only - managed by the Tinyproxy GUI
# CONTAINER_ALLOW_START
Allow 127.0.0.1
Allow 0.0.0.0/0
# CONTAINER_ALLOW_END

# ViaProxyName "tinyproxy"

# Domain-Blocking via Filter
Filter "/etc/tinyproxy/blocked-domains.txt"
# Filter based on domains (default), not URLs
FilterURLs Off

# Case-insensitive filtering
FilterCaseSensitive Off

FilterExtended On

# Upstream Proxy Configuration (optional)
# Managed by the Tinyproxy GUI
#Upstream 172.17.0.1:8889

# no upstream proxy for internal websites and unqualified hosts
#no upstream "docker.com"
#no upstream "github.com"

